WorkFlowToExecute: "Entity Load - Caregiver"
ExpectedReportFormat: "TABLE"
SPAProcessReference: "celltrak_client_caregiver_upload_dev"
APICredentialAsset: "APILogin"
AuthenticationURL: "oauth/token"
AddPatientURL: "api/v1.0/patient"
AddPractitionerURL: "api/v1.0/practitioner"
NumberOfRetries: "1"
RetryInterval: "00:00:02"
BaseAPIUrl: "https://api.uat-celltrak.io/"
AssignerValue: "e71c9adf-d2cb-4f79-af98-09e0653d5461"
ID_Filter: 
  - "39247"
JsonFilePath: "/Processes/Caregivers/EntityPayload-Caregivers.json"
BucketName: "Celltrak"
StorageFolderName: "Default"
FilePath: "LocationList.json"
Environment: "Testing"
ScratchPad_Fetch_Recordcount: "1000"
Connection: "Accredited"
Services: "Web Services"
CaregiverDetails:
  Category: "Operations"
  SubCategory: "Caregivers"
  SetFilters:
  - Operations:"Add/Update"
  - ItemName: "Office"
    ItemType: "dropdown"
  - ItemName: "Status"
    ItemType: "dropdown"
    ItemValue: "Active"
  SetFilters:
  - Operations:"Delete"
  - ItemName: "Office"
    ItemType: "dropdown"
  - ItemName: "Status"
    ItemType: "dropdown"
    ItemValue: "Terminated"  