WorkFlowToExecute: "Entity Load - Client"
ExpectedReportFormat: "TABLE"
SPAProcessReference: "celltrak_client_caregiver_upload_dev"
APICredentialAsset: "APILogin"
AuthenticationURL: "oauth/token"
AddPatientURL: "api/v1.0/patient"
AddPractitionerURL: "api/v1.0/practitioner"
NumberOfRetries: "1"
RetryInterval: "00:00:02"
BaseAPIUrl: "https://api.uat-celltrak.io/"
AssignerValue: "e71c9adf-d2cb-4f79-af98-09e0653d5461"
ManagingOrganizationValue: "12d6f77c-b897-4f12-bafd-5f23e28f4532"
BucketName: "Celltrak"
StorageFolderName: "Default"
FilePath: "LocationList.json"
ID_Filter: 
  - "44282"
  - "44283"
JsonFilePath: "/Processes/Clients/EntityPayload-Clients.json"
Environment: "Testing"
ScratchPad_Fetch_Recordcount: "1000"
Connection: "Accredited"
Services: "Web Services"
ClientDetails:
  Category: "Operations"
  SubCategory: "Clients"
  SetFilters:
  - ItemName: "Office"
    ItemType: "dropdown"
    ItemValue: "Training RC"
  - ItemName: "Status"
    ItemType: "dropdown"
    ItemValue: "Active"
SetFilters-Delete:
  - ItemName: "Office"
    ItemType: "dropdown"
  - ItemName: "Status"
    ItemType: "dropdown"
    ItemValue: "Discharged"     